language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- gem update --system $RUBYGEMS_VERSION
- gem --version
- gem install bundler
- bundle --version
bundler_args: --binstubs
script: 
- bin/rake build
- . test/setup_ubuntu.bash ; rvmsudo_secure_path=1 rvmsudo `env | egrep '^TRAVIS|PING2|UNREACHABLE'` bin/rake test
env:
  - LAP=1
  - LAP=2
  - LAP=3
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
